# Example file, must be customized with you own list of projects and DB/App IDs in each project
apiVersion: v1
kind: ConfigMap
metadata:
  name: auto-backup
  namespace: baserow
data:
  CONFIG: |
    retention: 10 # Global default retention
    backups:
    - project: ProjectA
      ids:
      - 18
    - project: ProjectB
      retention: 3 # Optional project level retention
      ids:
      - 201
      - 112
    - project: ProjectC
      ids:
      - 199