# The specified username must have access to all projects to backup
# It is recommended to create a dedicated user (autobackup) and invite this technical account in each project
apiVersion: v1
kind: Secret
metadata:
  name: auto-backup
  namespace: baserow
type: Opaque
stringData:
  CREDS: |
    username: <baserow username>
    password: <baserow password>
    email: <user email>
    api_url: "https://<your.baserow.host>/api/"
